apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: platform-app-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: platform-app-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: platform-app-clusterrole
  apiGroup: rbac.authorization.k8s.io
