apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: platform-app-clusterrole
rules:
  - apiGroups: [""]  # Core API group
    resources: ["namespaces", "pods", "services", "configmaps", "secrets"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  - apiGroups: ["apps"]  # For deployments and statefulsets
    resources: ["deployments", "statefulsets"]
    verbs: ["get", "list", "create", "update", "delete"]
