apiVersion: v1
kind: Service
metadata:
  name: k8s-platform-app-service
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30000
  selector:
    app: k8s-platform-app
